defaults:
  - model: QA/distilbert #retriever/RAG # dialog/dialogpt
  - _self_

raw: 
  path: data/raw/sample.csv

processed:
  dir: data/processed
  name: processed.csv
  path: ${processed.dir}/${processed.name}

final:
  dir: data/final
  name: final.csv
  path: ${final.dir}/${final.name}